### ISSUE TITLE
cawfree - Incorrect liquidity calculations when burning expired positions whose notional token does not use 18 decimals of precision.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-smilee-finance-judging#52]
cawfree

high

# Incorrect liquidity calculations when burning expired positions whose notional token does not use 18 decimals of precision.

## Summary

The function [`shareOfPayoff`](https://github.com/sherlock-audit/2024-02-smilee-finance/blob/3241f1bf0c8e951a41dd2e51997f64ef3ec017bd/smilee-v2-contracts/src/lib/Notional.sol#L120), used to compute the residual payoff for an expired position, mutates the input parameter [`Amount memory amount_`](https://github.com/sherlock-audit/2024-02-smilee-finance/blob/3241f1bf0c8e951a41dd2e51997f64ef3ec017bd/smilee-v2-contracts/src/lib/Notional.sol#L123C23-L123C30) resulting in miscalculations back up in the caller context.

## Vulnerability Detail

When a position is expired, the [`DVP`](https://github.com/sherlock-audit/2024-02-smilee-finance/blob/3241f1bf0c8e951a41dd2e51997f64ef3ec017bd/smilee-v2-contracts/src/DVP.sol) relies upon the function [`shareOfPayoff`](https://github.com/sherlock-audit/2024-02-smilee-finance/blob/3241f1bf0c8e951a41dd2e51997f64ef3ec017bd/smilee-v2-contracts/src/lib/Notional.sol#L120) when burning a position:

```solidity
// Compute the payoff to be paid:
Amount memory payoff_ = _liquidity[expiry].shareOfPayoff(strike, amount, _baseTokenDecimals);
paidPayoff = payoff_.getTotal();

// Account transfer of setted aside payoff:
_liquidity[expiry].decreasePayoff(strike, payoff_);
```

This results in the `amount` parameter passed into [`shareOfPayoff`](https://github.com/sherlock-audit/2024-02-smilee-finance/blob/3241f1bf0c8e951a41dd2e51997f64ef3ec017bd/smilee-v2-contracts/src/lib/Notional.sol#L120) running the risk of being mutated when handling non-wad decimals and possessing a non-zero `up` or `down` attribute, since the transformation is not unset.

For simplicity, let's consider the non-zero `up` attribute case:

```solidity
if (amount_.up > 0) {
  amount_.up = AmountsMath.wrapDecimals(amount_.up, decimals);
  used_.up = AmountsMath.wrapDecimals(used_.up, decimals);
  accountedPayoff_.up = AmountsMath.wrapDecimals(accountedPayoff_.up, decimals);

  // amount : used = share : payoff
  payoff_.up = (amount_.up*accountedPayoff_.up)/used_.up;
  payoff_.up = AmountsMath.unwrapDecimals(payoff_.up, decimals);
}
```

Notice here that the child property `up` of `amount_` is written to using `AmountsMath.wrapDecimals(amount_.up, decimals)`, meaning any value assignment here will additionally take affect in the caller's context as well as the local sequence since they are both referencing the same area of memory.

Normally when `decimals` are `18`, this sequence has no effect and returns the same value.

Conversely, for lesser token decimal precisions (i.e. USDC), [the value is scaled up](https://github.com/sherlock-audit/2024-02-smilee-finance/blob/3241f1bf0c8e951a41dd2e51997f64ef3ec017bd/smilee-v2-contracts/src/lib/AmountsMath.sol#L55):

```solidity
function wrapDecimals(uint256 amount, uint8 decimals) external pure returns (uint256) {
  if (decimals == _DECIMALS) {
    return amount;
  }
  if (decimals > _DECIMALS) {
    revert TooManyDecimals();
  }
  return amount * (10 ** (_DECIMALS - decimals));
}
```

Continuing with USDC as an example, an `amount_.up` value of `1e6` will be amplified into `1e6 * 1e12 = 1e18` not only within the scope of [`shareOfPayoff`](https://github.com/sherlock-audit/2024-02-smilee-finance/blob/3241f1bf0c8e951a41dd2e51997f64ef3ec017bd/smilee-v2-contracts/src/lib/Notional.sol#L120), but also in the scope of [`_burn`](https://github.com/sherlock-audit/2024-02-smilee-finance/blob/3241f1bf0c8e951a41dd2e51997f64ef3ec017bd/smilee-v2-contracts/src/DVP.sol#L231).

The result is that all subsequent reads of `amount.up` after the call to [`shareOfPayoff`](https://github.com/sherlock-audit/2024-02-smilee-finance/blob/3241f1bf0c8e951a41dd2e51997f64ef3ec017bd/smilee-v2-contracts/src/lib/Notional.sol#L120) are erroneously interacting with the scaled version, resulting in incorrect calculations for all subsequent references, such as calculation of the premium, sales fees and the application of position modifications.

## Impact

Due to this incorrect accounting, there are a wide range of affected values and resulting failures throughout the burn flow, including:

1. A significant amplification to `entryPremiumProp`, due to the numerator now being amplified but not the denominator.
2. Excessive fees paid to the `FeeManager`.
3. An exaggerated decrease of `Position` attributes.
  3.1 For smaller positions, this could result in `revert` through underflow.
  3.2 Though for whale positions, numerical underflow may be avoided and would instead convert into heavy loss for the owner.

## Code Snippet

```solidity
/**
 * @notice Get the share of residual payoff set aside for the given expired position
 * @param strike The position strike
 * @param amount_ The position notional
 * @param decimals The notional's token number of decimals
 * @return payoff_ The owed payoff
 * @dev It relies on the calls of decreaseUsage and decreasePayoff after each position is decreased
 */
function shareOfPayoff(
    Info storage self,
    uint256 strike,
    Amount memory amount_,
    uint8 decimals
) external view returns (Amount memory payoff_) {
    Amount memory used_ = self.used[strike];
    Amount memory accountedPayoff_ = self.payoff[strike];

    if (amount_.up > 0) {
        amount_.up = AmountsMath.wrapDecimals(amount_.up, decimals);
        used_.up = AmountsMath.wrapDecimals(used_.up, decimals);
        accountedPayoff_.up = AmountsMath.wrapDecimals(accountedPayoff_.up, decimals);

        // amount : used = share : payoff
        payoff_.up = (amount_.up * accountedPayoff_.up) / used_.up;
        payoff_.up = AmountsMath.unwrapDecimals(payoff_.up, decimals);
    }

    if (amount_.down > 0) {
        amount_.down = AmountsMath.wrapDecimals(amount_.down, decimals);
        used_.down = AmountsMath.wrapDecimals(used_.down, decimals);
        accountedPayoff_.down = AmountsMath.wrapDecimals(accountedPayoff_.down, decimals);

        payoff_.down = (amount_.down * accountedPayoff_.down) / used_.down;
        payoff_.down = AmountsMath.unwrapDecimals(payoff_.down, decimals);
    }
}
```

## Tool used

Foundry

## Recommendation

Ideally, a function call should avoid mutable writes to parameters unless the function accepts exclusive ownership of the parameter being passed, which indeed does not hold true for this scenario. In this regard, it is recommended that [`shareOfPayoff`](https://github.com/sherlock-audit/2024-02-smilee-finance/blob/3241f1bf0c8e951a41dd2e51997f64ef3ec017bd/smilee-v2-contracts/src/lib/Notional.sol#L120) should deep-clone the input `amount_` for the modifications necessary only to local calculations.

Failing this, it is advised that [`shareOfPayoff`](https://github.com/sherlock-audit/2024-02-smilee-finance/blob/3241f1bf0c8e951a41dd2e51997f64ef3ec017bd/smilee-v2-contracts/src/lib/Notional.sol#L120) should [`unwrapDecimals`](https://github.com/sherlock-audit/2024-02-smilee-finance/blob/3241f1bf0c8e951a41dd2e51997f64ef3ec017bd/smilee-v2-contracts/src/lib/AmountsMath.sol#L65) after the precision-sensitive calculations have been performed.

**Comment by cawfree** [comment]
Escalate

The `view` function modifier does not change how the memory model in Solidity fundamentally works.

In the context of a standard call, modifications to `memory` within a `view` function continue to be realized:

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Test} from "forge-std/Test.sol";

library MutableLibrary {

    struct SomeInputParameter {
        uint256 x;
    }

    /// @notice This view function takes an input parameter and assigns an internal value to it.
    function mutateInputParameters(SomeInputParameter memory someInputParameter) internal view {
        someInputParameter.x = 69;
    }

}

contract MutableContract {

    /// @dev We allocate a struct in memory from a public (non-view) function, and note that the modification
    /// to the parameter is realized. 
    function verifyInputParameterMutation() public view returns (uint256) {
        MutableLibrary.SomeInputParameter memory someInputParameter = MutableLibrary.SomeInputParameter({
          x: 420
        });
        MutableLibrary.mutateInputParameters(someInputParameter);
        return someInputParameter.x;
    }

}

contract TestParameterMutations is Test {

    function testParameterMutation() public {
        assert(new MutableContract().verifyInputParameterMutation() == 69);
    }

}
```

We can go even further and make the function `pure`:

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Test} from "forge-std/Test.sol";

library MutableLibrary {

    struct SomeInputParameter {
        uint256 x;
    }

    /// @notice This view function takes an input parameter and assigns an internal value to it.
    function mutateInputParameters(SomeInputParameter memory someInputParameter) internal pure {
        someInputParameter.x = 69;
    }

}

contract MutableContract {

    /// @dev We allocate a struct in memory from a public (non-view) function, and note that the modification
    /// to the parameter is realized. 
    function verifyInputParameterMutation() public pure returns (uint256) {
        MutableLibrary.SomeInputParameter memory someInputParameter = MutableLibrary.SomeInputParameter({
          x: 420
        });
        MutableLibrary.mutateInputParameters(someInputParameter);
        return someInputParameter.x;
    }

}

contract TestParameterMutations is Test {

    function testParameterMutation() public {
        assert(new MutableContract().verifyInputParameterMutation() == 69);
    }

}
```

Therefore Solidity **does not** discard modifications to `memory` (instead it throws on a `view` function's attempted writes to storage), and the raised issue is entirely plausible.


> [!NOTE]
>
> The Solidity [documentation on the `view` modifier](https://docs.soliditylang.org/en/v0.8.25/contracts.html#view-functions) prevents the following operations from taking place inside of a `view` function:
> 
> - Writing to state variables.
> - [Emitting events](https://docs.soliditylang.org/en/v0.8.25/contracts.html#events).
> - [Creating other contracts](https://docs.soliditylang.org/en/v0.8.25/control-structures.html#creating-contracts).
> - Using `selfdestruct`.
> - Sending Ether via calls.
> - Calling any function not marked `view` or `pure`.
> - Using low-level calls.
> - Using inline assembly that contains certain opcodes.

It should be emphasized that writing to `memory` is _not_ considered modifying state, since any writes to `memory` are disposed of. However, because the `library` we are using exposes `internal` functions, there is _no dedicated call context_ for the call, meaning the writes to memory in `shareOfPayoff` take place using the **same memory reference**.

Again referring to the toy example, if instead we were to specify `SomeInputParameter storage` instead of `SomeInputParameter memory`, compilation would fail with the following error:

```shell
Compiler run failed:
Error (8961): Function cannot be declared as view because this expression (potentially) modifies the state.
  --> test/Mutations.t.sol:16:9:
   |
16 |         someInputParameter.x = 69;
```

This is because `storage` parameters modify state, and `memory` parameters do not.

Therefore, the `Amount memory` is written to by the library and indeed influence the contents of the `struct` back up in the caller context, resulting in erroneous execution. This is because the `memory` parameter can provably be modified back up in the calling context.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> The `view` function modifier does not change how the memory model in Solidity fundamentally works.
> 
> In the context of a standard call, modifications to `memory` within a `view` function continue to be realized:
> 
> ```solidity
> // SPDX-License-Identifier: UNLICENSED
> pragma solidity ^0.8.13;
> 
> import {Test} from "forge-std/Test.sol";
> 
> library MutableLibrary {
> 
>     struct SomeInputParameter {
>         uint256 x;
>     }
> 
>     /// @notice This view function takes an input parameter and assigns an internal value to it.
>     function mutateInputParameters(SomeInputParameter memory someInputParameter) internal view {
>         someInputParameter.x = 69;
>     }
> 
> }
> 
> contract MutableContract {
> 
>     /// @dev We allocate a struct in memory from a public (non-view) function, and note that the modification
>     /// to the parameter is realized. 
>     function verifyInputParameterMutation() public view returns (uint256) {
>         MutableLibrary.SomeInputParameter memory someInputParameter = MutableLibrary.SomeInputParameter({
>           x: 420
>         });
>         MutableLibrary.mutateInputParameters(someInputParameter);
>         return someInputParameter.x;
>     }
> 
> }
> 
> contract TestParameterMutations is Test {
> 
>     function testParameterMutation() public {
>         assert(new MutableContract().verifyInputParameterMutation() == 69);
>     }
> 
> }
> ```
> 
> We can go even further and make the function `pure`:
> 
> ```solidity
> // SPDX-License-Identifier: UNLICENSED
> pragma solidity ^0.8.13;
> 
> import {Test} from "forge-std/Test.sol";
> 
> library MutableLibrary {
> 
>     struct SomeInputParameter {
>         uint256 x;
>     }
> 
>     /// @notice This view function takes an input parameter and assigns an internal value to it.
>     function mutateInputParameters(SomeInputParameter memory someInputParameter) internal pure {
>         someInputParameter.x = 69;
>     }
> 
> }
> 
> contract MutableContract {
> 
>     /// @dev We allocate a struct in memory from a public (non-view) function, and note that the modification
>     /// to the parameter is realized. 
>     function verifyInputParameterMutation() public pure returns (uint256) {
>         MutableLibrary.SomeInputParameter memory someInputParameter = MutableLibrary.SomeInputParameter({
>           x: 420
>         });
>         MutableLibrary.mutateInputParameters(someInputParameter);
>         return someInputParameter.x;
>     }
> 
> }
> 
> contract TestParameterMutations is Test {
> 
>     function testParameterMutation() public {
>         assert(new MutableContract().verifyInputParameterMutation() == 69);
>     }
> 
> }
> ```
> 
> Therefore Solidity **does not** discard modifications to `memory` (instead it throws on a `view` function's attempted writes to storage), and the raised issue is entirely plausible.
> 
> 
> > [!NOTE]
> >
> > The Solidity [documentation on the `view` modifier](https://docs.soliditylang.org/en/v0.8.25/contracts.html#view-functions) prevents the following operations from taking place inside of a `view` function:
> > 
> > - Writing to state variables.
> > - [Emitting events](https://docs.soliditylang.org/en/v0.8.25/contracts.html#events).
> > - [Creating other contracts](https://docs.soliditylang.org/en/v0.8.25/control-structures.html#creating-contracts).
> > - Using `selfdestruct`.
> > - Sending Ether via calls.
> > - Calling any function not marked `view` or `pure`.
> > - Using low-level calls.
> > - Using inline assembly that contains certain opcodes.
> 
> It should be emphasized that writing to `memory` is _not_ considered modifying state, since any writes to `memory` are disposed of. However, because the `library` we are using exposes `internal` functions, there is _no dedicated call context_ for the call, meaning the writes to memory in `shareOfPayoff` take place using the **same memory reference**.
> 
> Again referring to the toy example, if instead we were to specify `SomeInputParameter storage` instead of `SomeInputParameter memory`, compilation would fail with the following error:
> 
> ```shell
> Compiler run failed:
> Error (8961): Function cannot be declared as view because this expression (potentially) modifies the state.
>   --> test/Mutations.t.sol:16:9:
>    |
> 16 |         someInputParameter.x = 69;
> ```
> 
> This is because `storage` parameters modify state, and `memory` parameters do not.
> 
> Therefore, the `Amount memory` is written to by the library and indeed influence the contents of the `struct` back up in the caller context, resulting in erroneous execution. This is because the `memory` parameter can provably be modified back up in the calling context.
> 

You've deleted an escalation for this issue.

**Comment by cawfree** [comment]
Agreed, this issue is not valid.

The `library` function is `external` and not `internal`, meaning the function is allocated its own call context and therefore writes to the function parameter are local to the function call itself.

Many thanks!
